# coding: utf-8

"""
    merged spec

    merged spec  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import net_client
from net_client.api.servers_api import ServersApi  # noqa: E501
from net_client.rest import ApiException


class TestServersApi(unittest.TestCase):
    """ServersApi unit test stubs"""

    def setUp(self):
        self.api = net_client.api.servers_api.ServersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_server_options(self):
        """Test case for server_options

        Gets languages supported by the server generator  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
