# coding: utf-8

# flake8: noqa

"""
    Swagger Petstore

    This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.  # noqa: E501

    The version of the OpenAPI document: 1.0.6
    Contact: apiteam@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


__version__ = "1.0.0"

# import apis into sdk package
from net_client.api.pet_api import PetApi
from net_client.api.store_api import StoreApi
from net_client.api.user_api import UserApi

# import ApiClient
from net_client.api_response import ApiResponse
from net_client.api_client import ApiClient
from net_client.configuration import Configuration
from net_client.exceptions import OpenApiException
from net_client.exceptions import ApiTypeError
from net_client.exceptions import ApiValueError
from net_client.exceptions import ApiKeyError
from net_client.exceptions import ApiAttributeError
from net_client.exceptions import ApiException

# import models into sdk package
from net_client.models.api_response import ApiResponse
from net_client.models.category import Category
from net_client.models.order import Order
from net_client.models.pet import Pet
from net_client.models.tag import Tag
from net_client.models.user import User
